#!/usr/bin/env python

import sys

from multiprocessing.connection import Client

if __name__ == '__main__':
    if not sys.argv[1] or not sys.argv[2]:
        raise Exception("Usage: ./push <json-file> event ")

    if sys.argv[2] != "push":
        print("Only 'push' is supported")
        sys.exit(0)

    print("Adding to PopperCI queue: " + sys.argv[1])

    address = ('localhost', 6000)
    conn = Client(address)
    conn.send(sys.argv[1])
